import { IKnowledge } from "./typing/interfaces-and-enums";

export const KNOWLEDGE: IKnowledge[] = [
  {
    id: "typescript",
    label: "Typescript",
    academicExperience: ["TypeScript Fundamentals", "Advanced TypeScript"],
    workExperience: ["TypeScript in React 17+"],
  },
  {
    id: "css",
    label: "CSS",
    workExperience: ["CSS 3", "Responsive Design", "CSS Variables"],
    academicExperience: ["Tailwind CSS", "Material UI (basics)"],
  },
  {
    id: "react",
    label: "React",
    workExperience: ["React 15 (Component Class)", "4+ years of React 16+"],
    academicExperience: ["Server Components (basics)"],
  },
  {
    id: "nextjs",
    label: "Next.js",
    workExperience: ["Next.js 9+", "Next.js 11+"],
    academicExperience: ["Next.js 10"],
  },
  {
    id: "redux",
    label: "Redux",
    workExperience: ["Redux 3+", "Redux Toolkit"],
    academicExperience: ["Redux Fundamentals", "Redux Toolkit"],
  },
  {
    id: "testing",
    label: "Testing",
    workExperience: ["Jest", "React Testing Library", "Cypress"],
    academicExperience: ["Unit Testing", "Integration Testing"],
  },
  {
    id: "nodejs",
    label: "Node.js",
    workExperience: ["Node.js 12+", "Express.js"],
    academicExperience: ["Node.js Fundamentals", "Express.js"],
  },
  {
    id: "mongodb",
    label: "MongoDB",
    workExperience: ["MongoDB 4+", "Mongoose"],
    academicExperience: ["MongoDB Fundamentals", "Mongoose"],
  },
  {
    id: "git",
    label: "Git",
    workExperience: ["Git", "GitHub", "GitLab"],
    academicExperience: ["Git Fundamentals", "GitHub"],
  },
  {
    id: "docker",
    label: "Docker",
    workExperience: ["Docker", "Docker Compose"],
    academicExperience: ["Docker Fundamentals", "Docker Compose"],
  },
  {
    id: "graphql",
    label: "GraphQL",
    workExperience: ["Apollo Client", "GraphQL"],
    academicExperience: ["GraphQL Fundamentals", "Apollo Client"],
  },
  {
    id: "storybook",
    label: "Storybook",
    workExperience: ["Storybook"],
    academicExperience: ["Storybook Fundamentals"],
  },
  {
    id: "tailwindcss",
    label: "Tailwind CSS",
    workExperience: ["Tailwind CSS"],
    academicExperience: ["Tailwind CSS Fundamentals"],
  },
  {
    id: "materialui",
    label: "Material UI",
    workExperience: ["Material UI"],
    academicExperience: ["Material UI Fundamentals"],
  },
  {
    id: "websockets",
    label: "Websockets",
    workExperience: ["Websockets"],
    academicExperience: ["Websockets Fundamentals"],
  },
  {
    id: "rest",
    label: "REST",
    workExperience: ["REST"],
    academicExperience: ["REST Fundamentals"],
  },
  {
    id: "agile",
    label: "Agile",
    workExperience: ["Agile"],
    academicExperience: ["Agile Fundamentals"],
  },
  {
    id: "scrum",
    label: "Scrum",
    workExperience: ["Scrum"],
    academicExperience: ["Scrum Fundamentals"],
  },
  {
    id: "kanban",
    label: "Kanban",
    workExperience: ["Kanban"],
    academicExperience: ["Kanban Fundamentals"],
  },
  {
    id: "designpatterns",
    label: "Design Patterns",
    workExperience: ["Design Patterns"],
    academicExperience: ["Design Patterns Fundamentals"],
  },
  {
    id: "solid",
    label: "SOLID",
    workExperience: ["SOLID"],
    academicExperience: ["SOLID Fundamentals"],
  },
  {
    id: "cleanarchitecture",
    label: "Clean Architecture",
    workExperience: ["Clean Architecture"],
    academicExperience: ["Clean Architecture Fundamentals"],
  },
  {
    id: "tdd",
    label: "TDD",
    workExperience: ["TDD"],
    academicExperience: ["TDD Fundamentals"],
  },
  {
    id: "bdd",
    label: "BDD",
    workExperience: ["BDD"],
    academicExperience: ["BDD Fundamentals"],
  },
  {
    id: "ddd",
    label: "DDD",
    workExperience: ["DDD"],
    academicExperience: ["DDD Fundamentals"],
  },
  {
    id: "microservices",
    label: "Microservices",
    workExperience: ["Microservices"],
    academicExperience: ["Microservices Fundamentals"],
  },
  {
    id: "devops",
    label: "DevOps",
    workExperience: ["DevOps"],
    academicExperience: ["DevOps Fundamentals"],
  },
  {
    id: "aws",
    label: "AWS",
    workExperience: ["AWS"],
    academicExperience: ["AWS Fundamentals"],
  },
  {
    id: "azure",
    label: "Azure",
    workExperience: ["Azure"],
    academicExperience: ["Azure Fundamentals"],
  },
];
