import { IExperience } from "./typing/interfaces-and-enums";

export const experiences: IExperience[] = [
  {
    id: "enext",
    queryParams: [{ id: "enext" }],
    companyName: "Enext",
    description: [
      "Development of e-commerce stores for the Brazilian market",
      "Development of landing pages",
      "Development of Email Marketing templates",
      "Stack: HTML, CSS, SASS, CSS, Grunt, Gulp, jQuery, Invision, Photoshop, RunRun It, Github",
    ],
    endDate: "2017-07-01",
    position: "Frontend Developer",
    startDate: "2016-07-01",
    location: "São Paulo, SP, Brazil",
  },
  {
    id: "fiap",
    queryParams: [{ id: "fiap" }],
    companyName: "FIAP",
    description: [
      "Development of a SPA  Web-Based Platform with multi-web-browser support",
      "Agile methodology - Features development using Scrum",
      "Configuration of Front End build tools: Grunt + SASS",
      "Template Creationo with Angular JS",
      "Stack: ES6+, SCSS, Gulp, Grunt, Angular, Travis CI",
    ],
    endDate: "2018-05-12",
    position: "Frontend Developer",
    startDate: "2017-07-01",
    location: "São Paulo, SP, Brazil",
  },
  {
    id: "red-ventures",
    queryParams: [{ id: "red-ventures" }],
    companyName: "Red Ventures",
    description: [
      "Development of Web Applications - SPA",
      "CMS integrations with SPA pages",
      "Development of Internal NPM packages using private Github repos",
      "Configuration of Front End build tools: Webpack",
      "Migration of React Class Components to React Hooks",
      "CD/CI",
      "Stack: ES6+, CSS Modules, Webpack, React, Redux, Recompose, Stylus, Circle CI, Postman, Invision, Circle CI",
    ],
    endDate: "2019-11-01",
    position: "Frontend Engineer",
    startDate: "2018-05-12",
    location: "São Paulo, SP, Brazil",
  },
  {
    id: "origin",
    queryParams: [{ id: "origin" }],
    companyName: "Origin",
    description: [
      "Product development from the ground up",
      "Front end optimizations: Routing Code Splitting + Brotli Compression",
      "Deliverables Refinement and Prioritization",
      "Hiring Process - Pair interviews,Take-Home Assignments and development of a  Front End Assessment Project",
      "Mentoring new engineers",
      "Development of a SPA Web Application",
      "Analytics: Event definitions, Reports, Funnel, and Dashboards",
      "Configuration of Front End builds tools via Webpack",
      "Node CLI - Automatization of Folders, React Elements, and JS environments with Webpack",
      "Stack: ES6+, Typescript, Styled Components, Webpack, React, Redux, React Query, Heap Analytics, LaunchDarkly, Jest, Enzime, React Testing Library, Storybook, Figma, Jira, Github",
    ],
    endDate: null,
    position: "Frontend Engineer",
    startDate: "2019-12-01",
    location: "São Paulo, SP, Brazil",
  },
];
