/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SideProjectsIndexRouteImport } from './routes/side-projects/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SideProjectsIndexRoute = SideProjectsIndexRouteImport.update({
  id: '/side-projects/',
  path: '/side-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/side-projects/': typeof SideProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/side-projects': typeof SideProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/side-projects/': typeof SideProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience/' | '/knowledge/' | '/side-projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience' | '/knowledge' | '/side-projects'
  id: '__root__' | '/' | '/experience/' | '/knowledge/' | '/side-projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SideProjectsIndexRoute: typeof SideProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-projects/': {
      id: '/side-projects/'
      path: '/side-projects'
      fullPath: '/side-projects/'
      preLoaderRoute: typeof SideProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SideProjectsIndexRoute: SideProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
