/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as innerPagesRouteRouteImport } from './routes/(inner-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as innerPagesSkillsIndexRouteImport } from './routes/(inner-pages)/skills/index'
import { Route as innerPagesProjectsIndexRouteImport } from './routes/(inner-pages)/projects/index'
import { Route as innerPagesExperienceIndexRouteImport } from './routes/(inner-pages)/experience/index'
import { Route as innerPagesAboutIndexRouteImport } from './routes/(inner-pages)/about/index'

const innerPagesRouteRoute = innerPagesRouteRouteImport.update({
  id: '/(inner-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const innerPagesSkillsIndexRoute = innerPagesSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => innerPagesRouteRoute,
} as any)
const innerPagesProjectsIndexRoute = innerPagesProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => innerPagesRouteRoute,
} as any)
const innerPagesExperienceIndexRoute =
  innerPagesExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => innerPagesRouteRoute,
  } as any)
const innerPagesAboutIndexRoute = innerPagesAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => innerPagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/about/': typeof innerPagesAboutIndexRoute
  '/experience/': typeof innerPagesExperienceIndexRoute
  '/projects/': typeof innerPagesProjectsIndexRoute
  '/skills/': typeof innerPagesSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/about': typeof innerPagesAboutIndexRoute
  '/experience': typeof innerPagesExperienceIndexRoute
  '/projects': typeof innerPagesProjectsIndexRoute
  '/skills': typeof innerPagesSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(inner-pages)': typeof innerPagesRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/(inner-pages)/about/': typeof innerPagesAboutIndexRoute
  '/(inner-pages)/experience/': typeof innerPagesExperienceIndexRoute
  '/(inner-pages)/projects/': typeof innerPagesProjectsIndexRoute
  '/(inner-pages)/skills/': typeof innerPagesSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/about/'
    | '/experience/'
    | '/projects/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/about' | '/experience' | '/projects' | '/skills'
  id:
    | '__root__'
    | '/'
    | '/(inner-pages)'
    | '/api/chat'
    | '/(inner-pages)/about/'
    | '/(inner-pages)/experience/'
    | '/(inner-pages)/projects/'
    | '/(inner-pages)/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  innerPagesRouteRoute: typeof innerPagesRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(inner-pages)': {
      id: '/(inner-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof innerPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(inner-pages)/skills/': {
      id: '/(inner-pages)/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof innerPagesSkillsIndexRouteImport
      parentRoute: typeof innerPagesRouteRoute
    }
    '/(inner-pages)/projects/': {
      id: '/(inner-pages)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof innerPagesProjectsIndexRouteImport
      parentRoute: typeof innerPagesRouteRoute
    }
    '/(inner-pages)/experience/': {
      id: '/(inner-pages)/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof innerPagesExperienceIndexRouteImport
      parentRoute: typeof innerPagesRouteRoute
    }
    '/(inner-pages)/about/': {
      id: '/(inner-pages)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof innerPagesAboutIndexRouteImport
      parentRoute: typeof innerPagesRouteRoute
    }
  }
}

interface innerPagesRouteRouteChildren {
  innerPagesAboutIndexRoute: typeof innerPagesAboutIndexRoute
  innerPagesExperienceIndexRoute: typeof innerPagesExperienceIndexRoute
  innerPagesProjectsIndexRoute: typeof innerPagesProjectsIndexRoute
  innerPagesSkillsIndexRoute: typeof innerPagesSkillsIndexRoute
}

const innerPagesRouteRouteChildren: innerPagesRouteRouteChildren = {
  innerPagesAboutIndexRoute: innerPagesAboutIndexRoute,
  innerPagesExperienceIndexRoute: innerPagesExperienceIndexRoute,
  innerPagesProjectsIndexRoute: innerPagesProjectsIndexRoute,
  innerPagesSkillsIndexRoute: innerPagesSkillsIndexRoute,
}

const innerPagesRouteRouteWithChildren = innerPagesRouteRoute._addFileChildren(
  innerPagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  innerPagesRouteRoute: innerPagesRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
